[package]
name = "wrapp"
version = "0.1.3"
edition = "2024"
license = "MIT"
description = "Add additional functionality to Rust errors using a wrapper."
repository = "https://github.com/silvasch/wrapp.git"
documentation = "https://docs.rs/wrapp"

[dependencies]
